### PR TITLE
Update email templates

### PR DESCRIPTION
**Pull request by boshevski**
Using Salted responsive email template
https://github.com/rodriguezcommaj/salted
MIT License

### CODE REVIEW

**Comment by 161chihuahuas** [comment]
You'll need to host the images outside of here as the bridge (which imports this package) does not serve static assets.

**Comment by 161chihuahuas** [comment]
Probably can just put them on storj.io

**Comment by boshevski** [comment]
The images were already on storj.io and linked them in my previous commit "Fix Images". I just removed the image files now.

**Comment by boshevski** [comment]
Thanks for noticing, forgot about the image files.

**Comment by boshevski** [comment]
Also I'm not sure if we have to include separate license in the templates folder, or is it not necessary as the license is already there as a comment in the html files.

**Comment by 161chihuahuas** [comment]
Nah, as long as the license is left in tact in the source, i think it's fine. Merging!

**Comment by boshevski** [comment]
Cool, thanks.

**Pull request merged**
